# Generated by Django 4.2.3 on 2023-07-23 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature_unit",
                    models.CharField(
                        choices=[("Celsius", "Celsius"), ("Fahrenheit", "Fahrenheit")],
                        max_length=10,
                    ),
                ),
                (
                    "wind_speed_unit",
                    models.CharField(
                        choices=[("m/s", "m/s"), ("mph", "mph")], max_length=10
                    ),
                ),
                ("favorite_cities", models.ManyToManyField(to="weather.city")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
